version: '3'
services:
  app:
    container_name: app
    restart: always
    build: ./app
    ports:
      - 3001:3001
    volumes:
      - ./app/:/wrk
    depends_on:
      - mongodb

  mongodb:
    container_name: mongodb
    image: mongo:3.6.2
    volumes:
      - db-data:/var/lib/mongodb
    ports:
      - 27015:27015

  redis:
    image: "redis:alpine"

  client:
    container_name: client
    build: ./client
    ports:
      - '3000:3000'

  #ftp server
  ftp-server:
    build: ./ftp-server
    volumes:
      - /etc/pure-ftpd
      - /home/ftpusers
    environment:
      - FTP_PUBLIC_HOST=127.0.0.1
    ports:
      - "21:21"
      - "20:20"
      - "30000:30000"
      - "30001:30001"
      - "30002:30002"
      - "30003:30003"
      - "30004:30004"
      - "30005:30005"
      - "30006:30006"
      - "30007:30007"
      - "30008:30008"
      - "30009:30009"
    restart: always

  reverseproxy:
    build: ./nginx
    ports:
        - 8080:8080
        - 8081:8081
    restart: always

  nginx:
    depends_on:
        - reverseproxy
    image: nginx:alpine
    restart: always

  apache:
    depends_on:
        - reverseproxy
    image: httpd:alpine
    restart: always

volumes:
  db-data:
